#!/bin/sh

# Use POSIX time zone format so that we don't have to install the
# Olson timezone databases in the Docker image.  The trick is that we
# need to invert the hour offset from UTC for POSIX time.
TZ=$(date +%Z)$(( 12 - $(date -j -f %H%z 12+0000 +%k) ))

set -x # echo the next command
exec docker exec -e TERM -e TERM_PROGRAM -e TZ=$TZ -i -t $@ bash -l
